### Create

POST http://localhost:3333/book
Content-Type: application/json

{
    "name": "livro1",
    "description": "descrição do livro 1",
    "publishingCompany": "cedup",
    "shelf": {
        "id": "b76e50dc-1b19-4b81-af58-093deffaed3f"
    }
}

### List By Id

GET http://localhost:3333/book/<id>

### List All

GET http://localhost:3333/book

### Update

PUT http://localhost:3333/book/<id>
Content-Type: application/json

{
    "name": "",
    "description": "",
    "publishingCompany": "",
    "shelf": {
        "id": ""
    }
}

### Delete

DELETE http://localhost:3333/book/<id>